#Start(1730303172097)

  Warning number 33
  /Users/noasillam/rescript/clothes-app/src/components/Api.res:2:1-10

  1 │ // Api.res
  2 │ open Fetch
  3 │ 
  4 │ // Base URL de l'API

  unused open Fetch.


  We've found a bug for you!
  /Users/noasillam/rescript/clothes-app/src/components/ClothingList.res:9:5-23

   7 ┆ 
   8 ┆ React.useEffect1(() => {
   9 ┆   Api.fetchClothing()
  10 ┆   |> Js.Promise.then_(data  => {
  11 ┆ 

  This has type: promise<Js.Json.t>
  But this function argument is expecting: promise<array<'a> => array<'a>>
  
  The incompatible parts:
    Js.Json.t (defined as Js_json.t) vs array<'a> => array<'a>


  Warning number 33
  /Users/noasillam/rescript/clothes-app/src/HelloWorld.res:4:1-13

  2 │ open Header
  3 │ open ProductCard
  4 │ open Category
  5 │ open Footer
  6 │ 

  unused open Category.


  Warning number 33
  /Users/noasillam/rescript/clothes-app/src/HelloWorld.res:5:1-11

  3 │ open ProductCard
  4 │ open Category
  5 │ open Footer
  6 │ 
  7 │ // Exemple de données pour les catégories

  unused open Footer.


  Warning number 26
  /Users/noasillam/rescript/clothes-app/src/page/Home.res:4:15-22

  2 │ @react.component
  3 │ let make = () => {
  4 │   let (count, setCount) = React.useState(() => 0)
  5 │ 
  6 │   <div className="p-6">

  unused variable setCount.


  Warning number 26
  /Users/noasillam/rescript/clothes-app/src/page/Home.res:4:8-12

  2 │ @react.component
  3 │ let make = () => {
  4 │   let (count, setCount) = React.useState(() => 0)
  5 │ 
  6 │   <div className="p-6">

  unused variable count.

FAILED: cannot make progress due to previous errors.
#Done(1730303172221)
